INSERT INTO public.catalog_places (city, country, name, category, area, description, lat, lng, source)
SELECT * FROM (VALUES
('Séoul','Corée du Sud','Bukhansan National Park — 북한산국립공원','Balade','Gyeonggi-do / Séoul','Parc national sauvage et montagneux, très apprécié des Coréens : il abrite le plus haut sommet de Séoul. Randonnée de 2 à 5 h, niveau moyen à difficile, avec des variantes plus courtes. Temples cachés en forêt, vues spectaculaires sur la ville, ruisseaux, ponts et forêts de pins, à 20 min de transports. À voir : temple Doseonsa (gratuit, donations) et les portes anciennes de la forteresse Bukhansanseong. Matin conseillé.',37.6588,126.9776,'carnet'),
('Séoul','Corée du Sud','Bugaksan — 북악산 (murailles de Séoul)','Balade','Jongno-gu','Randonnée historique le long des murailles Nord de Séoul, avec vues sur les palais et le centre-ville. Portes traditionnelles et plateformes panoramiques ; la lumière du matin y est magnifique. À proximité : Gyeongbokgung (≈ 3 000 KRW), l’ancienne Maison Bleue (Cheong Wa Dae, fermée aux visites) et le temple Jogyesa (gratuit).',37.5977,126.9814,'carnet'),
('Séoul','Corée du Sud','Ansan Jarak-gil — 안산 자락길','Balade','Seodaemun-gu','Sentier en bois plat, très facile et agréable, autour de la montagne Ansan. Environ 1h30, accessible à tous, avec des zones de marche pieds nus. À proximité : petit temple Myeongji et quartier de Hongdae. Idéal le matin.',37.5747,126.9483,'carnet'),
('Séoul','Corée du Sud','Namsan Park — 남산공원','Vue','Jung-gu','Balade en forêt paisible et ombragée le matin, ou vue nocturne à 360° depuis la N Seoul Tower le soir. Sentiers pavés faciles, 30 à 60 min. Zones de réflexologie en pierre. Prix : parc et musée mémorial An Junggeun gratuits, téléphérique 14 000 KRW A/R (≈ 8 €), observatoire N Seoul Tower 21 000 KRW (≈ 12 €). À proximité : Namsangol Hanok Village (gratuit, 5-10 min à pied), Myeongdong, Jongno et les palais.',37.5512,126.9882,'carnet'),
('Séoul','Corée du Sud','Dream Forest — 북서울 꿈의숲','Balade','Gangbuk-gu','Grand parc au nord de Séoul, très calme et encore peu connu des touristes : observatoire panoramique gratuit, vastes forêts, étangs, jardins coréens et zones familiales. Sentiers forestiers faciles, parfaits pour une balade nature loin du centre. À proximité : petits temples locaux et accès pratique à Bukhansan.',37.6206,127.0432,'carnet'),
('Séoul','Corée du Sud','Huwon, le jardin secret de Changdeokgung — 창덕궁 후원','Culture','Jongno-gu','Classé UNESCO. Jardin royal secret avec l’étang Buyongji, pavillons royaux et forêt préservée aux arbres centenaires : une immersion rare dans le patrimoine naturel et architectural de Séoul. Prix : Secret Garden ≈ 10 000 KRW (5,76 €), Changdeokgung ≈ 3 000 KRW (1,73 €). À proximité : Changgyeonggung (≈ 3 000 KRW), sanctuaire Jongmyo (≈ 1 000 KRW) et Bukchon Hanok Village.',37.5826,126.9930,'carnet'),
('Séoul','Corée du Sud','Seoul Forest — 서울숲','Balade','Seongdong-gu','Grand parc urbain moderne : zones écologiques, jardins, longues pistes cyclables, enclos aux cerfs, serre tropicale, jardin des papillons et œuvres d’art. Ambiance jeune, cafés et street food tout autour. À proximité : petit temple Seongdong et quartier de Seongsu (cafés, friperies, ateliers créatifs).',37.5444,127.0374,'carnet'),
('Séoul','Corée du Sud','Yeouido Hangang Park — 여의도한강공원','Vue','Yeongdeungpo-gu','Parc emblématique au bord du fleuve Han : pique-nique, vélo, coucher de soleil et festivals. Ambiance locale vivante avec le classique poulet frit + bière en plein air, longues pistes cyclables et zones sportives. À proximité : 63 Building et son aquarium (≈ 28 000-30 000 KRW / 16-17 €) et le Yeouido Park pour une balade au calme. Beau du matin à la nuit.',37.5285,126.9337,'carnet'),
('Séoul','Corée du Sud','Seonyudo Park — 선유도공원','Balade','Yeongdeungpo-gu','Parc écologique sur une île du fleuve Han : ancienne usine de traitement d’eau transformée en espace design. Anciens bassins devenus jardins aquatiques, structures industrielles, passerelles et végétation. Ambiance zen, contemporaine et photogénique, peu touristique — promenade plutôt que randonnée. À proximité : Mangwon Market (street food) et Hongdae.',37.5432,126.8996,'carnet'),
('Séoul','Corée du Sud','Seokchon Lake Park — 석촌호수공원','Balade','Songpa-gu','Parc autour d’un lac urbain, célèbre pour ses cerisiers au printemps et ses reflets au coucher du soleil. Boucle de promenade facile, très fréquentée par les habitants, avec cafés tout autour. À proximité : Lotte World et le quartier de Jamsil.',37.5090,127.1000,'carnet'),
('Séoul','Corée du Sud','Mont Inwangsan — 인왕산','Vue','Jongno-gu','Randonnée rocheuse courte avec l’une des plus belles vues sur Séoul, le long des anciennes murailles. À proximité : temple Inwangsa (magnifique et gratuit), palais de Gyeongbokgung (3 000 KRW, gratuit en hanbok) et village de Seochon (ruelles, cafés, galeries). Matin conseillé.',37.5799,126.9585,'carnet'),
('Séoul','Corée du Sud','Banpo Hangang Park — 반포한강공원','Vue','Seocho-gu','Parc au bord du fleuve Han, à voir de nuit pour le spectacle de la fontaine arc-en-ciel du pont Banpo. Pelouses, pistes cyclables et food trucks : l’endroit parfait pour une soirée au bord de l’eau.',37.5100,126.9963,'carnet')
) AS v(city,country,name,category,area,description,lat,lng,source)
WHERE NOT EXISTS (SELECT 1 FROM public.catalog_places c WHERE c.name = v.name AND c.city = v.city);