insert into public.catalog_places (city, country, name, name_ko, category, area, description, lat, lng, best_time, price_info, sheet_key, source, website)
values
('Séoul','Corée du Sud','Palais Changgyeonggung','창경궁','Culture','Jongno-gu','Le plus intime des cinq grands palais, avec son étang Chundangji et la grande serre botanique de 1909. Relié à Changdeokgung par un passage.',37.5782,126.9946,ARRAY['Printemps (cerisiers)','Automne (feuillages)','Soirée illuminée'],'1 000 ₩ (~0,65 €) · gratuit en hanbok','changgyeonggung','seed',null),
('Séoul','Corée du Sud','Palais Unhyeongung','운현궁','Culture','Jongno-gu','Résidence princière du régent Heungseon Daewongun : cours paisibles, expositions et essais de hanbok, en pleine ville.',37.5750,126.9860,ARRAY['Toute l''année','Après-midi'],'Gratuit','unhyeongung','seed',null),
('Séoul','Corée du Sud','Tombes royales Seonjeongneung','선정릉','Culture','Gangnam-gu','Tombes royales Joseon classées UNESCO, îlot de forêt et de calme au cœur de Gangnam.',37.5100,127.0430,ARRAY['Automne','Matin'],'1 000 ₩ (~0,65 €)','seonjeongneung','seed',null),
('Séoul','Corée du Sud','Temple Bongwonsa','봉원사','Culture','Seodaemun-gu','Temple historique au pied de l''Ansan, berceau du bouddhisme Taego et du festival des fleurs de lotus.',37.5776,126.9403,ARRAY['Mai (lanternes)','Été (lotus)'],'Gratuit','bongwonsa','seed',null),
('Séoul','Corée du Sud','Temple Gilsangsa','길상사','Culture','Seongbuk-gu','Ancienne maison de thé transformée en temple, jardins en pente et programme de temple stay très apprécié.',37.5992,126.9967,ARRAY['Automne','Matin calme'],'Gratuit · temple stay payant','gilsangsa','seed',null),
('Séoul','Corée du Sud','Temple Hwagyesa','화계사','Culture','Gangbuk-gu','Temple du XVIe siècle au pied du Bukhansan, connu pour ses retraites de méditation en anglais.',37.6288,127.0106,ARRAY['Printemps','Automne'],'Gratuit','hwagyesa','seed',null),
('Séoul','Corée du Sud','Temple Jingwansa','진관사','Culture','Eunpyeong-gu','Un des quatre grands temples autour de Séoul, réputé pour sa cuisine monastique et son vallon boisé.',37.6390,126.9370,ARRAY['Automne','Week-end (repas monastique)'],'Gratuit · repas temple ~20 000 ₩ (~12,60 €)','jingwansa','seed',null),
('Séoul','Corée du Sud','Temple Doseonsa','도선사','Culture','Gangbuk-gu','Grand temple de montagne dans le parc du Bukhansan, avec son bouddha gravé dans la roche.',37.6486,127.0093,ARRAY['Printemps','Automne','Anniversaire de Bouddha'],'Gratuit','doseonsa','seed',null),
('Séoul','Corée du Sud','Temple Myogaksa','묘각사','Culture','Jongno-gu','Petit temple central sur le mont Naksan, idéal pour un temple stay court d''une nuit.',37.5747,127.0157,ARRAY['Toute l''année'],'Gratuit · temple stay ~50 000 ₩ (~31 €)','myogaksa','seed',null);