insert into public.catalog_places (city, country, name, name_ko, category, area, description, lat, lng, best_time, price_info, sheet_key, source)
values
('Busan','Corée du Sud','Musée national de Busan','부산박물관','Culture','Nam-gu','Histoire de la région du Gyeongsang, de la préhistoire aux échanges avec le Japon.',35.1290,129.0980,ARRAY['Toute l''année','Jour de pluie'],'Gratuit','busan-musee-national','seed'),
('Busan','Corée du Sud','Musée d''art de Busan','부산시립미술관','Culture','Haeundae-gu','Grand musée municipal d''art contemporain, voisin de l''espace Lee Ufan.',35.1690,129.1330,ARRAY['Toute l''année','Jour de pluie'],'Gratuit (expositions temporaires payantes)','busan-musee-art','seed'),
('Busan','Corée du Sud','MOCA Busan (art contemporain)','부산현대미술관','Culture','Saha-gu','Musée d''art contemporain sur l''île d''Eulsukdo, façade végétalisée et expositions engagées.',35.1080,128.9430,ARRAY['Toute l''année'],'Gratuit à 5 000 ₩ (~3,20 €)','busan-moca','seed'),
('Busan','Corée du Sud','Musée de la capitale provisoire','임시수도기념관','Culture','Seo-gu','Ancienne résidence présidentielle pendant la guerre de Corée, quand Busan était capitale.',35.1060,129.0170,ARRAY['Toute l''année'],'Gratuit','busan-capitale-provisoire','seed'),
('Busan','Corée du Sud','Cimetière commémoratif des Nations unies','유엔기념공원','Culture','Nam-gu','Seul cimetière onusien au monde : allées solennelles et jardins impeccables.',35.1240,129.0960,ARRAY['Matin','Automne'],'Gratuit','busan-un-memorial','seed'),
('Busan','Corée du Sud','Busan Cinema Center (Dureraum)','영화의전당','Culture','Haeundae-gu','Toit LED spectaculaire, siège du festival du film de Busan, séances en version originale.',35.1710,129.1290,ARRAY['Soirée','Octobre (BIFF)'],'Séance ~9 000 ₩ (~5,70 €)','busan-cinema-center','seed'),
('Busan','Corée du Sud','F1963 — usine devenue lieu culturel','에프1963','Culture','Suyeong-gu','Ancienne usine de câbles reconvertie en galeries, librairie, café et bambouseraie.',35.1780,129.1050,ARRAY['Après-midi','Jour de pluie'],'Gratuit','busan-f1963','seed'),
('Busan','Corée du Sud','Parc Yongdusan & Busan Tower','용두산공원 · 부산타워','Culture','Jung-gu','Colline centrale avec sa tour panoramique sur le port et le marché de Nampo.',35.1010,129.0320,ARRAY['Coucher de soleil','Soirée'],'Tour ~12 000 ₩ (~7,60 €) · parc gratuit','busan-yongdusan','seed'),
('Suncheon','Corée du Sud','Musée écologique de la baie de Suncheon','순천만 자연생태관','Culture','Suncheon-si','Centre d''interprétation des marais : oiseaux migrateurs, marées et roselières expliqués.',34.8850,127.5090,ARRAY['Hiver (grues)','Jour de pluie'],'Inclus dans le billet baie ~8 000 ₩ (~5,10 €)','suncheon-eco-musee','seed'),
('Suncheon','Corée du Sud','Musée d''art de Suncheon','순천시립미술관','Culture','Suncheon-si','Petit musée municipal : art contemporain coréen et artistes du Jeollanam-do.',34.9500,127.4870,ARRAY['Toute l''année'],'Gratuit','suncheon-musee-art','seed'),
('Autour de Suncheon','Corée du Sud','Aqua Planet Yeosu','아쿠아플라넷 여수','Culture','Yeosu','Grand aquarium de l''Expo 2012 : bélugas, tunnel océanique et otaries.',34.7530,127.7480,ARRAY['Jour de pluie','Matin'],'~29 000 ₩ (~18,30 €)','yeosu-aquaplanet','seed'),
('Autour de Suncheon','Corée du Sud','Musée coréen du thé (Boseong)','한국차박물관','Culture','Boseong','Trois étages consacrés à la culture du thé, dégustation et vue sur les terrasses.',34.7290,127.0790,ARRAY['Printemps','Après la plantation'],'~1 000 ₩ (~0,65 €)','boseong-musee-the','seed'),
('Autour de Suncheon','Corée du Sud','Pavillon Jinnamgwan (Yeosu)','진남관','Culture','Yeosu','Plus vaste pavillon en bois de Corée, quartier général naval de l''amiral Yi Sun-sin.',34.7410,127.7400,ARRAY['Toute l''année','Coucher de soleil'],'Gratuit','yeosu-jinnamgwan','seed'),
('Autour de Séoul','Corée du Sud','Musée d''art Hoam (Yongin)','호암미술관','Culture','Yongin','Collection d''art ancien coréen dans un jardin traditionnel Hee Won, superbe en automne.',37.2130,127.2070,ARRAY['Automne','Printemps'],'~10 000 ₩ (~6,30 €)','yongin-hoam','seed'),
('Autour de Séoul','Corée du Sud','Village folklorique coréen (Yongin)','한국민속촌','Culture','Yongin','Village Joseon reconstitué : maisons, artisans, spectacles équestres et scènes de tournage.',37.2590,127.1180,ARRAY['Printemps','Automne'],'~32 000 ₩ (~20,20 €)','yongin-village-folklorique','seed'),
('Autour de Séoul','Corée du Sud','MMCA Gwacheon','국립현대미술관 과천','Culture','Gwacheon','Antenne du musée d''art contemporain au pied du mont Cheonggyesan, entourée de sculptures.',37.4330,127.0170,ARRAY['Automne','Jour de pluie'],'~2 000 ₩ (~1,30 €)','gwacheon-mmca','seed');